everyone_dies: false # Set true if everyone should die if someone dies
random_kill_count: 1 # Set how many players should die if everyone_dies is false
enabled_worlds: # Worlds where if a player die, others die
  - "world"
  - "world_nether"
  - "world_the_end"
immune_players: # UUIDs of players who are immune to being killed
  